### ISSUE TITLE
uninitialized constant Warden (NameError)

### ISSUE THREAD

**Issue by halorium** [ajsharp/warden-rspec-rails#3]
I did exactly as the README instructed and ran my tests and this is the error I received.

It seems it's not being loaded but not sure what should be required and where.

Thank you.

**Comment by ajsharp** [comment]
What versions of rspec, rails and warden are you running?

**Comment by atomaka** [comment]
I experienced the same issue, @ajsharp.

```
rspec-core (3.4.3)
rspec-rails (3.4.2)
rails (4.2.5.1)
warden (1.2.6)
warden-rspec-rails (0.2.0)
```

Corrected by requiring your helpers in my `spec_helper.rb`:

```
require 'warden/test/controller_helpers' 
```

Although I'm still experiencing the issue that I was hoping `warden-rspec-rails` would resolve: 

```
Failure/Error: warden.user

     NoMethodError:
       undefined method `user' for nil:NilClass
```

**Comment by ajsharp** [comment]
@atomaka My apologies, I haven't used this gem in some time, and don't have the time at the moment to try to debug this. If you're able to come up with a solution, I'd very appreciative and would welcome the patch.

**Comment by nstoker** [comment]
I currently have the same issue, @atomaka . Did you find a solution?

I have a [repository](https://github.com/nstoker/RubyOnRailsWindowsWoes) containing my code so far.

**Comment by atomaka** [comment]
@nstoker Unfortunately, I cannot remember :\  It looks like I am still using this gem in the project I was working on at the time, but do not have `require 'warden/test/controller_helpers'` used anywhere.  I skimmed my code and commits, but could not find anything specific to this issue.

**Comment by A-Boudi** [comment]
The Rspec file should login the user. If you're using FactoryBot, add the following line before your tests.
`before { warden.set_user FactoryBot.create(:user) }`

**Comment by ajsharp** [comment]
I'm not sure what the problem or solution is here, but if someone has a PR I'm happy to pull it in.

**Comment by BrianHawley** [comment]
The NameError is fixed by putting `require "warden"` in the test helper file before the code. If you're using Bundler and/or RubyGems properly, declaring the "warden" gem in Gemfile before "warden-rspec-rails", and not overriding the `require` option of the gem declarations, it won't need this, but there's no need to assume that is the case.

The NoMethodError is solved by making sure the middleware name check will work with both `Warden::Manager` and `RailsWarden::Manager`. I checked the commit history and that name check seems to go back and forth requiring only one or the other name. In #9 I changed the code to `m.name.include?('Warden::Manager')` to support both.
